[package]
authors = [
    "Without Boats <lee@libertad.ucsd.edu>",
    "Pascal Hertleif <killercup@gmail.com>",
    "Sebastian Garrido <sebasgarcep@gmail.com>",
    "Jonas Platte <mail@jonasplatte.de>",
    "Benjamin Gill <git@bgill.eu>",
    "Andronik Ordian <write@reusable.software>",
]
categories = [
    "development-tools",
    "development-tools::cargo-plugins",
]
description = "This extends Cargo to allow you to add and remove dependencies by modifying your `Cargo.toml` file from the command line. It contains `cargo add`, `cargo rm`, and `cargo upgrade`."
documentation = "https://github.com/killercup/cargo-edit/blob/master/README.md#available-subcommands"
homepage = "https://github.com/killercup/cargo-edit"
keywords = [
    "cargo",
    "cargo-subcommand",
    "cli",
    "dependencies",
    "crates",
]
license = "Apache-2.0/MIT"
name = "cargo-edit"
readme = "README.md"
repository = "https://github.com/killercup/cargo-edit"
version = "0.6.0"
edition = "2018"

[[bin]]
name = "cargo-add"
path = "src/bin/add/main.rs"
required-features = ["add"]

[[bin]]
name = "cargo-rm"
path = "src/bin/rm/main.rs"
required-features = ["rm"]

[[bin]]
name = "cargo-upgrade"
path = "src/bin/upgrade/main.rs"
required-features = ["upgrade"]

[badges.appveyor]
repository = "killercup/cargo-edit"

[badges.travis-ci]
repository = "killercup/cargo-edit"

[dependencies]
atty = { version = "0.2.14", optional = true }
cargo_metadata = "0.9.1"
dirs = "2.0.2"
env_proxy = "0.4.0"
error-chain = "0.12.2"
failure = "0.1.7"
git2 = "0.13.0"
hex = "0.4.2"
regex = "1.3.5"
serde = "1.0.105"
serde_derive = "1.0.105"
serde_json = "1.0.48"
structopt = { version = "0.3.12", optional = true }
subprocess = "0.2.4"
termcolor = "1.1.0"
toml = "0.5.6"
toml_edit = "0.1.5"
url = "2.1.1"
ureq = "1.3.0"

[dependencies.semver]
features = ["serde"]
version = "0.9.0"

[dev-dependencies]
assert_cli = "0.6.3"
pretty_assertions = "0.6.1"
tempfile = "3.1.0"

[features]
default = [
    "add",
    "rm",
    "upgrade",
]
add = ["cli"]
rm = ["cli"]
upgrade = ["cli"]
cli = ["atty", "structopt"]
test-external-apis = []
